# Grunt aliases
---
# Build everything
build:
  - 'build:i18n'
  - 'build:js'

'build-watch':
  - 'shell:composer-install'
  - 'build:js'
  - 'watch'

# Build JavaScript from assets to production
'build:js':
  - 'clean:jsDistFiles'
  - 'webpack:buildDev'

# Create a zipped artifact from a fresh build
'artifact':
  - 'shell:composer-install'
  - 'update-version'
  - 'release'
  - 'shell:composer-install-production'
  - 'clean:artifact'
  - 'copy:artifact'
  - 'compress:artifact'
  - 'shell:composer-install-dev'

'release':
  - 'release:js'
  - 'build:i18n'
'release:js':
  - 'clean:jsDistFiles'
  - 'webpack:buildProd'

'update-changelog:file':
  - 'get-latest-pr-texts'
  - 'update-changelog-with-latest-pr-texts'

'update-changelog:qa':
  - 'get-latest-pr-texts'
  - 'download-qa-changelog'
  - 'build-qa-changelog'

'update-changelog:all':
  - 'get-latest-pr-texts'
  - 'update-changelog-with-latest-pr-texts'
  - 'download-qa-changelog'
  - 'build-qa-changelog'

# Default task
default:
  - build
