# Grunt aliases
---
# Build everything
build:
  - 'build:js'

'build-watch':
  - 'shell:composer-install'
  - 'build:js'
  - 'watch'


# Build JavaScript from assets to production
'build:js':
  - 'clean:jsDistFiles'
  - 'webpack:buildDev'

# Create a zipped artifact from a fresh build
'artifact':
  - 'shell:composer-install'
  - 'update-version'
  - 'release'
  - 'shell:composer-install-production'
  - 'clean:artifact'
  - 'copy:artifact'
  - 'compress:artifact'
  - 'shell:composer-install-dev'

'release':
  - 'release:js'

'release:js':
  - 'clean:jsDistFiles'
  - 'webpack:buildProd'

# Default task
default:
  - build
