# Grunt aliases
---
# Build everything
build:
  - 'build:i18n'
  - 'build:js'
# Build internationalisation features
'build:i18n':
  - 'addtextdomain'
  - 'makepot'
  - 'glotpress_download'
# Build JSplugin files
'build:js':
  - 'browserify'
  - 'uglify'
# Check health of the project
check:
  - 'eslint'
  - 'jsonlint'
  - 'phplint'
  - 'phpcs'
  - 'checktextdomain'
# Create a zipped artifact from a fresh build
'create:artifact':
  - 'update-version'
  - 'build'
  - 'copy:artifact'
  - 'compress:artifact'
# Copy the needed files to the ./artifact folder
'copy:artifact':
  - 'copy:artifactFiles'
# Create a compressed zip from the ./artifact folder
'compress:artifact':
  - 'compress:artifactFiles'
# Default task
default:
  - build
