language: php

sudo: false

branches:
  only:
    - master
    - trunk

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: WP_VERSION=4.8 WP_MULTISITE=1 PHPLINT=1 PHPCS=1
    - php: 5.2
      env: WP_VERSION=4.8 WP_MULTISITE=1 PHPLINT=1
    - php: 5.3
      env: WP_VERSION=4.6
    - php: 5.6
      env: WP_VERSION=4.6
    - php: 7.1
      env: WP_VERSION=4.8
    - php: 5.2
      env: WP_VERSION=master
    - php: nightly
      env: WP_VERSION=master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
- PLUGIN_SLUG=$(basename $(pwd))
- export WP_DEVELOP_DIR=/tmp/wordpress/

# Clone WordPress
- git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress

# Copy news seo to the test directory
- cd ..
- cp -r "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
- cd /tmp/wordpress/
- cp wp-tests-config-sample.php wp-tests-config.php
- sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
- sed -i "s/yourusernamehere/travis/" wp-tests-config.php
- sed -i "s/yourpasswordhere//" wp-tests-config.php
- mysql -e "CREATE DATABASE wordpress_tests;" -uroot
- git clone https://github.com/squizlabs/PHP_CodeSniffer.git phpcs
- git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wpcs
- cd phpcs
- scripts/phpcs --config-set installed_paths ../wpcs
- cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
- phpenv local 5.6
- composer selfupdate 1.0.0 --no-interaction
- if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" || $TRAVIS_PHP_VERSION == "nightly" ]]; then composer require --dev phpunit/phpunit ^5.7; fi
- composer install --no-interaction
- composer config-yoastcs
- phpenv local --unset
- phpenv rehash

script:
- if [[ "$PHPLINT" == "1" ]]; then find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l; fi
- if [[ "$PHPCS" == "1" ]]; then vendor/bin/phpcs -v; fi
- phpunit -c phpunit.xml
