# Grunt aliases
---
# Build everything
build:
  - 'build:i18n'
  - 'build:js'

# Build internationalisation features
'build:i18n':
  - 'addtextdomain'
  - 'makepot'
  - 'glotpress_download'

# Build JSplugin files
'build:js':
  - 'clean:jsDistFiles'
  - 'webpack:buildDev'

# Check health of the project
check:
  - 'eslint'
  - 'jsonlint'
  - 'phplint'
  - 'phpcs'
  - 'checktextdomain'

# Create a zipped artifact from a fresh build
'artifact':
  - 'shell:production-composer-install'
  - 'update-version'
  - 'release'
  - 'clean:artifact'
  - 'copy:artifact'
  - 'compress:artifact'

'release':
  - 'release:js'
  - 'build:i18n'
'release:js':
  - 'clean:jsDistFiles'
  - 'webpack:buildProd'
# Default task
default:
  - build
