# Grunt aliases
---
# Build everything
build:
  - 'build:i18n'
  - 'build:js'

# Build JavaScript from assets to production
'build:js':
  - 'clean:jsDistFiles'
  - 'webpack:buildDev'

# Create a zipped artifact from a fresh build
'artifact':
  - 'shell:composer-install-production'
  - 'update-version'
  - 'release'
  - 'clean:artifact'
  - 'copy:artifact'
  - 'compress:artifact'
  - 'shell:composer-install-dev'

'release':
  - 'release:js'
  - 'build:i18n'
'release:js':
  - 'clean:jsDistFiles'
  - 'webpack:buildProd'
# Default task
default:
  - build
